### ISSUE TITLE
`global name 'strip_file' is not defined` in HPR UI

### ISSUE THREAD

**Issue by bzamecnik** [bzamecnik/sms-tools#53]
```
Traceback (most recent call last):
  File "/Users/bzamecnik/anaconda/envs/nsw_smst/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/Users/bzamecnik/anaconda/envs/nsw_smst/lib/python2.7/site-packages/smst/ui/models/hprModel_GUI_frame.py", line 140, in <lambda>
    'output_sounds/' + strip_file(self.filelocation.get()) + '_hprModel_sines.wav'), bg="gray30",
NameError: global name 'strip_file' is not defined
```

**Comment by bzamecnik** [comment]
Fixed import in `hprModel_GUI_frame.py` in 3216ef521a6dfc944858b6e1b6d90a190932d94d.
